import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MockPhasesDataTypeService {

  getMockData() {
    return [
      {
        id: 1,
        ra: 1,
        number_of_pages_explaining: 6,
        explaining_phase_page_1: "Ah, olá, jovem aventureiro! Bem-vindo ao Vale das Variáveis, onde as poções mágicas são criadas com um toque de programação! Hoje, vamos preparar uma poção especial.",
        //explaining_phase_page_1: "a",
        explaining_phase_page_2: "Mas cuidado, não podemos misturar os ingredientes de qualquer jeito. Cada ingrediente aqui representa um tipo de dado diferente, e precisamos escolher com sabedoria para que a poção funcione corretamente.",
        explaining_phase_page_3: "Você sabe o que são variáveis? Deixa eu te explicar de forma simples! Uma variável é como uma caixinha onde guardamos informações importantes para usar na nossa programação.",
        explaining_phase_page_4: "Dependendo do tipo de informação que queremos guardar, usamos um tipo de caixinha diferente. Aqui no Portugol, temos algumas caixinhas especiais, ou melhor, tipos de variáveis, o qual iremos descobrir com o passar das fases.",
        explaining_phase_page_5: `Cadeia: O tipo "cadeia", é como um colar de letras e símbolos. Pode guardar palavras inteiras ou frases, como "Olá, Mundo!", utilizando aspas duplas. No Portugol, usamos "cadeia" para criar essa caixinha especial.`,
        explaining_phase_page_6: `Agora que você conhece o tipo "cadeia", vamos preparar nossa poção! Cada ingrediente corresponde a um tipo de variável e precisamos escolher o tipo "cadeia". Sua missão é escolher o ingrediente certo e colocá-lo no caldeirão.`,
        data_type: "CADEIA",
        number_of_pages_phases: 4,
        variables_page_1: ["verdadeiro", "7", `"Olá mundo"`, `"Quero almoçar"`, `"bicicleta"`, "101110"],
        correct_answers_page_1: [`"Olá mundo"`, `"Quero almoçar"`, `"bicicleta"`],
        variables_page_2: [`"cor azul"`, `"correr"`, "10", `"pescar peixe"`, "falso", "00001111", "nulo"],
        correct_answers_page_2: [`"cor azul"`,`"correr"`, `"pescar peixe"`],
        variables_page_3: [`"cor amarela"`, "14", `"lua"`, "verdadeiro", "falso", `"pular corda"`],
        correct_answers_page_3: [`"cor amarela"`, `"lua"`, `"pular corda"`],
        variables_page_4: [`"nadar no mar"`, "20.00", `"flor girassol"`, "nulo", `"estrela"`, "101010"],
        correct_answers_page_4: [`"nadar no mar"`, `"flor girassol"`, `"estrela"`],
        number_of_pages_questions: 1,
        knowledge_validation_question: "O CodeSauro quer anotar o nome da poção que ele fez hoje. Qual tipo de variável ele deve usar para armazenar essa informação?",
        knowledge_validation_answers: ["Inteiro", "Real", "Cadeia", "Caractere"],
        knowledge_validation_correct_answer: "Cadeia",
      },
      {
        id: 2,
        ra: 1,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: `Você arrasou com o tipo Cadeia! Agora vamos aprender um novo tipo de variável, o tipo "inteiro".`,
        explaining_phase_page_2: `Imagine que você precisa guardar um número que não tem nenhuma parte quebrada, como 3, 42 ou 100. Esse número é chamado de "inteiro". No Portugol, usamos a palavra "inteiro" para criar uma caixinha que guarda números inteiros.`,
        data_type: "INTEIRO",
        number_of_pages_phases: 4,
        variables_page_1: [`"nota de dinheiro"`, "16", "90.00", "83", `"salão de beleza"`, "1", "44"],
        correct_answers_page_1: ["16", "83", "1", "44"],
        variables_page_2: ["11", '"banco"', "62", "23.12", "0", "1334.12"],
        correct_answers_page_2: ["11", "62", "0"],
        variables_page_3: [`"dez"`, "10.00", "10", `"10"`,`"dez reais"`],
        correct_answers_page_3: ["10"],
        variables_page_4: [`"94`, "81", "45", "12.01", "treze", `"17"`, "837"],
        correct_answers_page_4: ["81", "45", "837"],
        number_of_pages_questions: 1,
        knowledge_validation_question: "O CodeSauro quer guardar o número de poções que ele fez hoje. Qual tipo de variável ele deve usar para armazenar essa informação?",
        knowledge_validation_answers: ["Inteiro", "Cadeia", "Caractere", "Real"],
        knowledge_validation_correct_answer: "Inteiro",
      },
      {
        id: 3,
        ra: 1,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: `Agora que você aprendeu sobre o tipo "inteiro", vamos aprender o tipo "real".`,
        explaining_phase_page_2: `Vamos pensar no tipo "inteiro". Mas se o número tiver uma parte quebrada, como 3.14 ou 2.5? Para esses números, usamos o tipo "real". Esse tipo de variável guarda números com vírgula, que também chamamos de "números decimais".`,
        data_type: "REAL",
        number_of_pages_phases: 3,
        variables_page_1: ["43", "3.4", "11.11", "47", "1000", "6.54", `"1.1"`],
        correct_answers_page_1: ["3.4", "11.11", "6.54"],
        variables_page_2: ["100.00", "100", "1,000,000.00", `"mil"`, "3.14"],
        correct_answers_page_2: ["100.00", "1,000,000.00", "3.14"],
        variables_page_3: [`"54.34`, "34.1", "03", "71", `"quatro ponto dois"`, "2.5", "54.34", "12.3"],
        correct_answers_page_3: ["34.1", "54.34", "2.5", "12.3"],
        number_of_pages_questions: 1,
        knowledge_validation_question: "O CodeSauro mediu seu caldeirão e cabe 12.5 litros. Qual tipo de variável ele deve usar para armazenar essa informação?",
        knowledge_validation_answers: ["Caractere", "Cadeia", "Inteiro", "Real"],
        knowledge_validation_correct_answer: "Real",
      },
      {
        id: 4,
        ra: 1,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 5,
        ra: 1,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 6,
        ra: 1,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 7,
        ra: 1,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 8,
        ra: 1,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 9,
        ra: 2,
        context_phase: "Leve a operação aritmética:",
        number_of_pages_explaining: 4,
        explaining_phase_page_1: `Bem-vindo, bravo aventureiro! Estamos nas Montanhas Aritméticas, um lugar onde apenas aqueles que dominam a magia dos números podem encontrar o tesouro escondido.`,
        explaining_phase_page_2: `Para abrir esses baús do tesouro, precisamos descobrir as senhas mágicas. Essas senhas são operações matemáticas incompletas que você precisa resolver!`,
        explaining_phase_page_3: `Ah, e aqui nas Montanhas Aritméticas, usamos operadores aritméticos, como o + (mais), - (menos), * (multiplicação) e / (divisão) para fazer os números se comportarem como queremos.”`,
        explaining_phase_page_4: `Lembre-se, cada baú tem uma operação diferente, e você pode usar essas operações para descobrir os tesouros escondidos. Pronto para o desafio? Vamos abrir todos os baús juntos!`,
        number_of_pages_phases: 4,
        variables_page_1: ["+", "-", "*", "/"],
        variables_numbers_page_1: ["5", "3", "=", "8"],
        correct_answers_page_1: ["+"],
        variables_page_2: ["+", "-", "*", "/"],
        variables_numbers_page_2: ["12", "3", "=", "4"],
        correct_answers_page_2: ["/"],
        variables_page_3: ["+", "-", "*", "/"],
        variables_numbers_page_3: ["14", "5", "=", "9"],
        correct_answers_page_3: ["-"],
        variables_numbers_page_4: ["2", "3", "=", "6"],
        variables_page_4: ["+", "-", "*", "/"],
        correct_answers_page_4: ["*"],
        number_of_pages_questions: 1,
        knowledge_validation_question: "O CodeSauro precisa dividir um tesouro igualmente entre seus três amigos. O total do tesouro é de 60 moedas de ouro. Qual operação deve usar para descobrir quantas moedas cada amigo vai receber?",
        knowledge_validation_answers: ["60 * 3", "60 – 3", "60 / 3", "60 + 3"],
        knowledge_validation_correct_answer: "60 / 3",
      },
      {
        id: 10,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 11,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 12,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 13,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 14,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 15,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 16,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 17,
        ra: 2,
        context_phase: "Leve a operação correta:",
        number_of_pages_explaining: 3,
        explaining_phase_page_1: `Ah, bem-vindo de volta, jovem aventureiro! Agora os baús do tesouro não são protegidos apenas por simples números ou operações aritméticas. As fechaduras mágicas desses baús exigem que você pense de maneira lógica.`,
        explaining_phase_page_2: `Essas fechaduras são inteligentes. Elas usam operadores como MAIOR (>), MENOR (<) e IGUAL (==).`,
        explaining_phase_page_3: `O seu trabalho é usar esses operadores para descobrir as combinações corretas. Cada baú tem sua própria lógica, e você precisará aplicar essas regras para abrir todos eles e encontrar os tesouros escondidos!`,
        number_of_pages_phases: 4,
        variables_page_1: ["+", "-", ">", "<", "=="],
        variables_numbers_page_1: ["5", "(3", "+","4)"],
        correct_answers_page_1: ["<"],
        variables_page_2: ["+", "-", ">", "<", "=="],
        variables_numbers_page_2: ["6", "(2", "*", "3)"],
        correct_answers_page_2: ["=="],
        variables_page_3: ["+", "-", ">", "<", "=="],
        variables_numbers_page_3: ["(10", "2)", "<", "10"],
        correct_answers_page_3: ["+"],
        variables_numbers_page_4: ["3", "(8","/", "2)"],
        variables_page_4: ["+", "-", ">", "<", "=="],
        correct_answers_page_4: ["<"],
        number_of_pages_questions: 1,
        knowledge_validation_question: "O CodeSauro está tentando abrir um baú que só se abrirá se a condição for verdadeira. Qual das opções abaixo resultará em VERDADEIRO?",
        knowledge_validation_answers: ["5 > 8", "7 < 2", "6 > 4", "9 == 10"],
        knowledge_validation_correct_answer: "6 > 4",
      },
      {
        id: 18,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 19,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 20,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 21,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 22,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 23,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 24,
        ra: 2,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 25,
        ra: 3,
        number_of_pages_explaining: 3,
        explaining_phase_page_1: "Chegamos ao temível Labirinto Condicional. Este labirinto é cheio de surpresas, e só aqueles que dominam as estruturas condicionais podem encontrar a saída. Cada curva, cada bifurcação, precisa de uma decisão inteligente baseada no que você vê ao redor",
        explaining_phase_page_2: `Aqui, você precisa usar as estruturas SE e SE NÃO para decidir o que fazer em cada situação. Se há um caminho livre, seguimos em frente. Mas, se encontramos um obstáculo, talvez seja hora de tentar outra direção.`,
        explaining_phase_page_3: `Seu desafio é organizar os blocos na ordem correta para que possamos sair desse labirinto em segurança! Cada decisão conta, então pense bem antes de agir. Vamos lá, aventureiro, mostre que você é capaz de dominar o labirinto com a sua lógica impecável!`,
        number_of_pages_phases: 1,
        variables_page_1: ["seguir reto", "seguir ao lado", "SE caminho livre", "SE NÃO"],
        correct_answers_page_1: ["SE caminho livre", "seguir reto", "SE NÃO", "seguir ao lado"],
        maze_configuration_1: [
          { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" },
          { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "green" }, { class: "green" }, { class: "red", content: "B" },
          { class: "red", content: "A" }, { class: "green" }, { class: "green" }, { class: "green" }, { class: "invisible" }, { class: "invisible" },
          { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }
        ],
        number_of_pages_questions: 1,
        knowledge_validation_question: "O CodeSauro encontrou uma bifurcação no labirinto. Ele precisa continuar caminhado, mas seguir reto o caminho está bloqueado. Qual condinção o Codesauro precisa usar para continuar caminhando?",
        knowledge_validation_answers: ["SE caminho ocupado, seguir reto", "SE caminho ocupado, seguir a direita", "SE caminho livre, seguir reto", "SE caminho livre, seguir a direita"],
        knowledge_validation_correct_answer: "SE caminho ocupado, seguir a direita",
      },
      {
        id: 26,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 27,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 28,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 29,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 30,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 31,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 32,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 33,
        ra: 3,
        number_of_pages_explaining: 5,
        explaining_phase_page_1: "Olá, bravo aventureiro! Chegamos às Cavernas do Loop, uma parte especial do labirinto onde o caminho se repete de várias maneiras. Para atravessar essa área, precisamos usar os laços de repetição.",
        explaining_phase_page_2: `Laços de repetição são comandos que permitem repetir uma mesma ação várias vezes até que uma condição seja atendida ou até que o caminho esteja livre.`,
        explaining_phase_page_3: `Por exemplo, imagine que você precisa andar 10 passos para sair de um corredor longo. Em vez de dizer para andar um passo de cada vez, podemos usar um laço de repetição para dizer: 'Continue andando até chegar ao final do corredor'.`,
        explaining_phase_page_4: `Aqui você pode usar laços de repetição como ENQUANTO e PARA. O comando ENQUANTO continua repetindo uma ação enquanto uma condição for verdadeira. Já o comando PARA define um número específico de repetições.`,
        explaining_phase_page_5: `Seu desafio aqui é usar esses laços de repetição para fazer o CodeSauro repetir movimentos de forma inteligente e sair do labirinto. Mostre sua habilidade com os laços de repetição e ajude o CodeSauro a escapar!”`,
        number_of_pages_phases: 1,
        variables_page_1: ["caminhar", `"SE caminho = "B"`, "ENQUANTO caminho", "parar"],
        correct_answers_page_1: ["ENQUANTO caminho", "caminhar", `"SE caminho = "B"`, "parar"],
        maze_configuration_1: [
          { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" },
          { class: "red", content: "A" }, { class: "green" }, { class: "green" }, { class: "green" }, { class: "green" }, { class: "red", content: "B" },
          { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" },
          { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }, { class: "invisible" }
        ],
        number_of_pages_questions: 1,
        knowledge_validation_question: "O CodeSauro precisa dar exatamente 4 passos em frente. Qual é o laço de repetição correto para garantir que ele faça isso?",
        knowledge_validation_answers: ["ENQUANTO caminho livre, andar", "PARA cada passo de 1 até 4, andar", "SE caminho livre, andar 4 vezes", "PARA cada passo de 1 até 3, andar"],
        knowledge_validation_correct_answer: "PARA cada passo de 1 até 4, andar",
      },
      {
        id: 34,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 35,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 36,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 37,
        ra: 5,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 38,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 39,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      },
      {
        id: 40,
        ra: 3,
        number_of_pages_explaining: 2,
        explaining_phase_page_1: "em breve...",
        explaining_phase_page_2: "em breve...",
        number_of_pages_phases: 4,
        variables_page_1: ["em breve..."],
        correct_answers_page_1: ["em breve..."],
        variables_page_2: ["em breve..."],
        correct_answers_page_2: ["em breve..."],
        variables_page_3: ["em breve..."],
        correct_answers_page_3: ["em breve..."],
        variables_page_4: ["em breve..."],
        correct_answers_page_4: ["em breve..."],
        number_of_pages_questions: 1,
        knowledge_validation_question: "em breve...",
        knowledge_validation_answers: ["em breve...", "em breve...", "em breve...", "em breve..."],
        knowledge_validation_correct_answer: "em breve...",
      }
    ];
  }
}
